apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: minha-aplicacao
  template:
    metadata:
      labels:
        app: minha-aplicacao
    spec:
      containers:
      - name: minha-aplicacao
        image: gabrielg11/projeto_atv_docker:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: app-config
